### ISSUE TITLE
Minimum AWS credentials required?

### ISSUE THREAD

**Issue by technion** [gophergala2016/goad#4]
Hi,

Just wondering if you could clarify the roles required in the AWS credentials.

I try to keep separate IAM profiles with minimum credentials available but aren't sure what needs to be allocated here.

Any assistance appreciated.

Edit: I've managed to get it down to these roles:
AmazonSQSFullAccess 
AWSLambdaFullAccess 
IAMFullAccess

Is it possible to cache, or precreate the IAM, so that that access can be removed?

**Comment by jcxplorer** [comment]
After the first run (where it creates the IAM role and role policy), the only IAM permission you'll need is GetRole.

In a future release we can even skip that GetRole check if we find that the lambda function already exists.

**Comment by technion** [comment]
Thanks!
